---
version: '3.8'
services:
   
   gtp2tg:
     image: lucmichalski/gtp2tg:cpu-latest
     container_name: ${NAMESPACE}-telegram
     build:
       context: .
       dockerfile: Dockerfile
     command: ["python3", "src/GPT2-Learning.py"]     
